name-template: 'v$NEXT_PATCH_VERSION 🌈'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'area/dependencies'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## What's New
  $CHANGES

  ## 👨🏽‍💻 Contributors

  Thank you to our contributors for making this release possible:
  $CONTRIBUTORS