name: push on dockerhub
on: 
  workflow_dispatch:
    inputs: 
      tag:
        description: 'tag of the image'
        required: true
        default: 'latest'
      branch:
        description: 'checkout branch to build image'
        required: true
        default: 'master'
      
     
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          ref: '${{ github.event.inputs.branch }}'
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: '${{ github.event.inputs.tag }}'